source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'wwgs' do
  config = use_native_modules!
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'





  
  use_react_native!(:path => config["reactNativePath"])

  target 'wwgsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'wwgs-tvOS' do
  # Pods for wwgs-tvOS

  target 'wwgs-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
